"""Curate the final e2e/judge-calibration/evals/labels.yaml.

Distinct, deliberate, human-triggered step: the mined pool is 663 candidates
but calibration only needs a curated ~20-50. Export only ever includes
candidates that are BOTH graded (pass/fail, not TODO) AND explicitly marked
"include" by the human -- never automatic, never everything.
"""
from __future__ import annotations

from pathlib import Path

from . import labels_store

EXPORT_HEADER = """\
# CURATED — human-reviewed judge-calibration labels for e2e/judge-calibration.
#
# Generated by the judge-calibration grader app's export action from the
# mined pool at e2e/judge-calibration/mined/candidates.jsonl. Contains only
# candidates that a human explicitly graded (pass/fail) AND explicitly
# marked for inclusion in the calibration set -- this is a deliberately
# curated subset, not the full mined pool.
#
# Shape matches feature-e-judge-calibration/design.md's labels.yaml: a flat
# { id: pass|fail } map.
"""


def curate(
    order: list[str],
    labels: dict[str, str],
    included: dict[str, bool],
) -> dict[str, str]:
    """Return the {id: label} map for ids that are graded AND marked included."""
    return {
        cid: labels[cid]
        for cid in order
        if labels.get(cid) in ("pass", "fail") and included.get(cid)
    }


def export_curated_labels(
    order: list[str],
    labels: dict[str, str],
    included: dict[str, bool],
    dest_path: Path,
) -> dict[str, str]:
    """Curate and atomically write the real evals/labels.yaml. Returns the curated map."""
    curated = curate(order, labels, included)
    curated_order = [cid for cid in order if cid in curated]
    labels_store.write_labels_atomic(dest_path, curated, curated_order, header=EXPORT_HEADER)
    return curated
