"""Load evals/judges.yaml: the registry of real judge assertions discovered
from e2e/*/evals/*.yaml (one entry per judge, keyed by ``judge_id``).

This app is stdlib-only (no PyYAML, no pip installs -- see the grader
README), but judges.yaml is not the flat ``id: value`` shape labels.yaml is:
it is a block sequence of mappings, generated by a fixed script
(``discover_judges.py``) with a fixed, known field set and a fixed
multi-line single-quoted scalar style for the long-form ``prompt`` field.
Rather than write a general-purpose YAML parser, this module is a
hand-rolled parser for exactly that fixed shape -- the same "narrow parser
for a narrow, machine-generated schema" approach ``labels_store.py`` and
``conversation_draft.py`` take. If a future regeneration of judges.yaml
changes the shape (field order, indentation, or scalar style), this parser
is expected to raise a clear ``ValueError`` rather than silently
misinterpret the file.

The loaded ``judge_id`` set doubles as (half of) the security allowlist:
``JudgeRegistry.is_known_id`` is checked before any judge id is used to
resolve a matrix cell or a filesystem path (see ``backend/app.py``).
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

_JUDGE_START_RE = re.compile(r"^- ([a-z_]+): ?(.*)$")
_FIELD_RE = re.compile(r"^  ([a-z_]+): ?(.*)$")
_KEYWORD_ITEM_RE = re.compile(r"^  - ([a-z_]+): ?(.*)$")
_KEYWORD_FIELD_RE = re.compile(r"^    ([a-z_]+): ?(.*)$")

# The exact field set discover_judges.py emits per judge, in this order.
_EXPECTED_FIELDS = (
    "judge_id",
    "suite",
    "suite_file",
    "case_name",
    "case_when",
    "prompt",
    "keywords",
    "needs_human_review",
)


def _unquote_plain(value: str) -> Any:
    """Decode a plain (unquoted) or simple-quoted single-line YAML scalar."""
    value = value.strip()
    if value == "null" or value == "":
        return None
    if value == "true":
        return True
    if value == "false":
        return False
    if len(value) >= 2 and value[0] == "'" and value[-1] == "'":
        return value[1:-1].replace("''", "'")
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        return value[1:-1]
    return value


def _scan_single_quoted_chunk(s: str) -> tuple[str, str, bool]:
    """Scan one physical line's worth of a single-quoted scalar.

    Returns ``(content, rest_after_terminator, terminated)``. ``''`` inside
    the line decodes to a literal ``'`` and does not terminate the scalar; a
    lone ``'`` does.
    """
    buf: list[str] = []
    i = 0
    while i < len(s):
        if s[i] == "'":
            if i + 1 < len(s) and s[i + 1] == "'":
                buf.append("'")
                i += 2
                continue
            return "".join(buf), s[i + 1 :], True
        buf.append(s[i])
        i += 1
    return "".join(buf), "", False


def _parse_folded_single_quoted(
    lines: list[str], start_index: int, base_indent: int, first_segment: str
) -> tuple[str, int]:
    """Parse a YAML single-quoted scalar folded across multiple physical
    lines (PyYAML's default style for a long plain string containing literal
    newlines: each embedded newline becomes a blank line in the dump, and a
    genuine line-wrap without a blank folds to a single space).

    ``first_segment`` is the text after ``key: `` on the key's own line
    (including the opening quote). Returns ``(decoded_value, next_index)``
    where ``next_index`` is the index of the first line after the scalar.
    """
    if not first_segment.startswith("'"):
        raise ValueError(f"expected single-quoted scalar, got: {first_segment!r}")

    chunks: list[str] = []
    pending = ""
    started = False

    def emit(chunk: str) -> None:
        nonlocal pending, started
        if started:
            chunks.append(pending if pending else " ")
        else:
            started = True
        chunks.append(chunk)
        pending = ""

    content, _rest, terminated = _scan_single_quoted_chunk(first_segment[1:])
    emit(content)
    if terminated:
        return "".join(chunks), start_index

    idx = start_index
    while True:
        if idx >= len(lines):
            raise ValueError("unterminated single-quoted scalar in judges.yaml")
        raw = lines[idx]
        if raw.strip() == "":
            pending += "\n"
            idx += 1
            continue
        if raw[:base_indent] != " " * base_indent:
            raise ValueError(
                f"expected continuation line indented {base_indent} spaces, got: {raw!r}"
            )
        dedented = raw[base_indent:]
        content, _rest, terminated = _scan_single_quoted_chunk(dedented)
        emit(content)
        idx += 1
        if terminated:
            return "".join(chunks), idx


def _parse_keywords_block(lines: list[str], start_index: int, end_index: int) -> list[dict[str, str]]:
    """Parse the ``- value: ...\\n    polarity: ...\\n    source: ...``
    items between ``start_index`` (first item line) and ``end_index``
    (exclusive, the following ``needs_human_review:`` line)."""
    keywords: list[dict[str, str]] = []
    idx = start_index
    current: dict[str, str] | None = None
    while idx < end_index:
        line = lines[idx]
        item_match = _KEYWORD_ITEM_RE.match(line)
        if item_match:
            if current is not None:
                keywords.append(current)
            current = {item_match.group(1): _unquote_plain(item_match.group(2))}
            idx += 1
            continue
        field_match = _KEYWORD_FIELD_RE.match(line)
        if field_match and current is not None:
            current[field_match.group(1)] = _unquote_plain(field_match.group(2))
            idx += 1
            continue
        raise ValueError(f"unrecognized line inside keywords block: {line!r}")
    if current is not None:
        keywords.append(current)
    return keywords


def parse_judges_yaml(text: str) -> list[dict[str, Any]]:
    """Parse the ``judges:`` block sequence out of judges.yaml text."""
    lines = text.split("\n")
    # Drop a trailing artifact from a trailing newline in the source text.
    if lines and lines[-1] == "":
        lines = lines[:-1]

    start_indices = [i for i, line in enumerate(lines) if _JUDGE_START_RE.match(line)]
    if not start_indices:
        raise ValueError("judges.yaml: no '- judge_id: ...' entries found")

    judges: list[dict[str, Any]] = []
    for block_i, start in enumerate(start_indices):
        end = start_indices[block_i + 1] if block_i + 1 < len(start_indices) else len(lines)
        block = list(lines[start:end])
        # Normalize the first line ("- judge_id: x") to look like every
        # other field line ("  judge_id: x") so one regex covers both.
        block[0] = "  " + block[0][2:]

        record: dict[str, Any] = {}
        idx = 0
        while idx < len(block):
            line = block[idx]
            if line.strip() == "":
                idx += 1
                continue
            m = _FIELD_RE.match(line)
            if not m:
                raise ValueError(f"judges.yaml: unrecognized field line: {line!r}")
            key, rest = m.group(1), m.group(2)
            if key == "prompt":
                value, idx = _parse_folded_single_quoted(block, idx + 1, base_indent=4, first_segment=rest)
                record[key] = value
                continue
            if key == "keywords":
                if rest.strip() == "[]":
                    record[key] = []
                    idx += 1
                    continue
                # Scan forward to the next top-level field line to find the
                # extent of this block sequence.
                j = idx + 1
                while j < len(block) and (
                    _KEYWORD_ITEM_RE.match(block[j]) or _KEYWORD_FIELD_RE.match(block[j])
                ):
                    j += 1
                record[key] = _parse_keywords_block(block, idx + 1, j)
                idx = j
                continue
            record[key] = _unquote_plain(rest)
            idx += 1

        missing = [f for f in _EXPECTED_FIELDS if f not in record]
        if missing:
            raise ValueError(f"judges.yaml entry {record.get('judge_id')!r} missing fields: {missing}")
        judges.append(record)

    return judges


class JudgeRegistry:
    """Loaded judges.yaml, indexed by ``judge_id``.

    The id set doubles as the judge-id half of the security allowlist (see
    module docstring and ``backend/app.py``).
    """

    def __init__(self, yaml_path: Path):
        self.yaml_path = Path(yaml_path)
        self._by_id: dict[str, dict[str, Any]] = {}
        self._order: list[str] = []
        self.reload()

    def reload(self) -> None:
        text = self.yaml_path.read_text(encoding="utf-8")
        judges = parse_judges_yaml(text)
        by_id: dict[str, dict[str, Any]] = {}
        order: list[str] = []
        for judge in judges:
            jid = judge["judge_id"]
            if jid in by_id:
                raise ValueError(f"duplicate judge_id in judges.yaml: {jid!r}")
            by_id[jid] = judge
            order.append(jid)
        self._by_id = by_id
        self._order = order

    @property
    def order(self) -> list[str]:
        return list(self._order)

    @property
    def ids(self) -> set[str]:
        """The judge-id allowlist."""
        return set(self._by_id.keys())

    def is_known_id(self, judge_id: str) -> bool:
        return judge_id in self._by_id

    def get(self, judge_id: str) -> dict[str, Any] | None:
        return self._by_id.get(judge_id)

    def __len__(self) -> int:
        return len(self._order)
