name: CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integration:
    name: Integration tests
    strategy:
      matrix:
        os:
          # - macos-latest,
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build CLI
        run: npm run build

      - name: Run integration tests
        run: ./integ/integ.bat
        shell: cmd
        env:
          AILLY_ENGINE: noop
        if: runner.os == 'Windows'

      - name: Run integration tests
        run: ./integ/integ.sh
        env:
          AILLY_ENGINE: noop
        if: runner.os == 'Linux'
