name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  extension-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install && npx tsc -p core && npm link ./core -w extension

      - name: Build all workspaces
        run: npm run build

      - name: Run CI script in extension workspace
        run: npm run --workspace extension ci
