name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  npm-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install && npx tsc -p core && npm link ./core -w cli

      - name: Run CI script in cli workspace
        run: npm run --workspace cli ci

      - name: Run CI script in core workspace
        run: npm run --workspace core ci
